$bg = rgb(282828)
$red = rgb(cc241d)
$green = rgb(98971a)
$yellow = rgb(d79921)
$blue = rgb(458588)
$purple = rgb(b16286)
$aqua = rgb(689d6a)
$gray = rgb(a89984)

$active_border = rgba(d79921ee) rgba(fe8019ee) 45deg
$inactive_border = rgba(504945aa)
