source = ~/.config/hypr/colors.conf

monitor=,1920x1080@144,auto,1.0

$terminal = kitty
$fileManager = nautilus
$menu = wofi

source = ~/.config/hypr/autorun.conf

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = ELECTRON_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

source = ~/.config/hypr/general.conf


input {
    kb_layout = us, ru
    kb_variant =
    kb_options = grp:win_space_toggle, caps:none
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}


gesture = 3, horizontal, workspace

source = ~/.config/hypr/keybinds.conf

source = ~/.config/hypr/workspaces.conf

source = ~/.config/hypr/windowrules.conf
