workspace = 2-99, monitor:DP-1, default:true
workspace = 1, monitor:HDMI-A-1

workspace = special:music, on-created-empty:chromium --new-window "https://music.youtube.com/" & pavucontrol
workspace = special:magic, on-created-empty:obsidian

